leg1_project:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 25

  joint_group_position_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - joint1
        - joint2
        - joint3
    gains:
        joint1 : {p: 180, d: 0.9, i: 20} 
        joint2 : {p: 180, d: 0.9, i: 20} 
        joint3 : {p: 180, d: 0.9, i: 20} 

  # Position Controllers - joint1 ---------------------------------------
#  joint1_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint1
#    pid: {p: 180, d: 0.9, i: 20} 

  # Position Controllers - joint2 ---------------------------------------
#  joint2_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint2
#    pid: {p: 180, d: 0.9, i: 20}

  # Position Controllers - joint3 ---------------------------------------
#  joint3_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint3
#    pid: {p: 180, d: 0.9, i: 20} 
